# Generated by Django 5.1.5 on 2025-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='file',
            field=models.FileField(upload_to='coaching_files/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(default=22, upload_to='course_files/'),
            preserve_default=False,
        ),
    ]
