# Generated by Django 5.1.5 on 2025-06-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='homepage_videos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Page Video',
                'verbose_name_plural': 'Home Page Videos',
            },
        ),
    ]
