# Generated by Django 5.1.5 on 2025-03-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_otp_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('forgot', 'Forgot'), ('update', 'Update')], max_length=100, null=True),
        ),
    ]
