# Generated by Django 5.1.5 on 2025-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish_to',
            field=models.CharField(choices=[('construction', 'Construction Management Success'), ('aline', 'Aline Marin'), ('both', 'Both')], default='construction', help_text='Select the sites to publish this blog to.', max_length=20),
        ),
    ]
