# Generated by Django 5.1.5 on 2025-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_publish_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_to',
            field=models.CharField(choices=[('construction', 'Construction Management Success'), ('alin', 'Aline Marin'), ('both', 'Both')], default='construction', help_text='Select the sites to publish this blog to.', max_length=20),
        ),
    ]
