# Generated by Django 4.2.11 on 2025-05-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_bouncedemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BouncedEmail',
        ),
    ]
