# Generated by Django 5.1.5 on 2025-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lead_magnet_image', models.ImageField(upload_to='popup_images/')),
                ('lead_magnet_pdf', models.FileField(upload_to='lead_magnets/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
