# Generated by Django 5.1.5 on 2025-02-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
