# Generated by Django 5.1.5 on 2025-02-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_alter_subscriber_name_alter_subscriber_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
