# Generated by Django 5.1.5 on 2025-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_alter_subscriber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='topic',
            field=models.CharField(blank=True, choices=[('courses', 'Courses'), ('consulting', 'Consulting'), ('coaching', 'Coaching'), ('speaking', 'Speaking')], max_length=100, null=True),
        ),
    ]
