# Generated by Django 5.1.5 on 2025-10-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempDownload',
            new_name='OrderDownloadToken',
        ),
    ]
