"""
Django settings for alin_marin_books project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*', 'upward-emu-trivially.ngrok-free.app']

CSRF_TRUSTED_ORIGINS = ["https://bulldog-prompt-starling.ngrok-free.app ", "http://localhost/aline_marin/wordpress/", "https://alinmarin.com"]

CORS_ALLOWED_ORIGINS = [
    "https://alinmarin.com",
    "http://localhost",  # WordPress local dev
    "http://127.0.0.1",  # Optional if you use it
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'model_utils',
    'corsheaders',

    'web',
    'api.user',
    'api.service',
    'api.faq',
    'api.blog',
    'api.tags',
    'api.subscribers',
    'django_filters',
    'api.calendy',
    'api.notification',
    'api.subsriber_popup',
    'api.bounced_emails',
    'api.home_page_content'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'alin_marin_books.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'alin_marin_books.context_processors.get_tags',
                'alin_marin_books.context_processors.subscribed_topics',
            ],
        },
    },
]

WSGI_APPLICATION = 'alin_marin_books.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  
#         'NAME': os.environ.get('POSTGRES_DB', 'alin_marin_books_db_test'),  
#         'USER': os.environ.get('POSTGRES_USER', 'alin_marin_books_user_test'),
#         'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'admin'),
#         'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
#         'PORT': os.environ.get('POSTGRES_PORT', '5432'), 
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.environ.get("STATIC_ROOT", default=os.path.join(BASE_DIR, "staticfiles"))

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_PROFILE_IMAGE = "default-profile.png"

AUTH_USER_MODEL = "user.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

# Email Backend
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST = os.environ.get("EMAIL_HOST")
# EMAIL_PORT = os.environ.get("EMAIL_PORT")
# EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD") 
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Mailgun Email Configuration

USE_MAILGUN = os.environ.get('USE_MAILGUN', False) == "True"

if USE_MAILGUN:
    EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND")
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
    MAILGUN_API_KEY = os.environ.get("MAILGUN_API_KEY")
    MAILGUN_DOMAIN = os.environ.get("MAILGUN_DOMAIN")
    MAILGUN_SENDER_DOMAIN = os.environ.get("MAILGUN_SENDER_DOMAIN")
    MAILGUN_WEBHOOK_SIGNING_KEY = os.environ.get("MAILGUN_WEBHOOK_SIGNING_KEY")
else:
    EMAIL_BACKEND = os.environ.get("GMAIL_EMAIL_BACKEND")
    EMAIL_HOST = os.environ.get("GMAIL_EMAIL_HOST")
    EMAIL_PORT = os.environ.get("GMAIL_EMAIL_PORT")
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get("GMAIL_EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("GMAIL_EMAIL_HOST_PASSWORD") 
    DEFAULT_FROM_EMAIL = os.environ.get("GMAIL_DEFAULT_FROM_EMAIL")


CONTACT_EMAIL = os.environ.get("CONTACT_EMAIL")
RECAPTCHA_SECERET_KEY = os.environ.get("RECAPTCHA_SECERET_KEY")
RECAPTCHA_SITE_KEY = os.environ.get("RECAPTCHA_SITE_KEY")

CSRF_TRUSTED_ORIGINS = ["https://upward-emu-trivially.ngrok-free.app"]


# WordPress Creds
WORDPRESS_SITE_URL = os.environ.get("WORDPRESS_SITE_URL")
WORDPRESS_USERNAME = os.environ.get("WORDPRESS_USERNAME")  
WORDPRESS_APPLICATION_PASSWORD = os.environ.get("WORDPRESS_APPLICATION_PASSWORD") 
ENV = os.environ.get("ENV") 

# celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
BASE_URL = os.environ.get("BASE_URL")

MAX_VIDEO_UPLOAD_SIZE = 104857600  # 100MB in bytes
# For file upload handling
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_VIDEO_UPLOAD_SIZE
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_VIDEO_UPLOAD_SIZE




# INSTALLED_APPS += ['corsheaders']
# MIDDLEWARE = ['corsheaders.middleware.CorsMiddleware'] + MIDDLEWARE
CORS_ALLOW_ALL_ORIGINS = True 